// docs/src/.vuepress/theme/layouts/NotFound.vue
<template>
  <Layout :sidebar-items="sidebarItems">
    <div class="NotFound">
      <img src="/images/Lost-File-v4.gif" />
      <p><strong>404s suck!</strong> And we're sorry for this one.</p>
      <p>
        Good thing the permaweb has
        <a href="https://ardrive.io/fragility-of-the-internet/" target="_blank" rel="noreferrer">
          no more 404s
        </a>
      </p>
    </div>
  </Layout>
</template>

<script>
import Layout from "./Layout";

export default {
  name: "NotFound",
  components: {
    Layout,
  },
  computed: {
    sidebarItems() {
      const { themeConfig } = this.$site;
      // Use the root ("/") sidebar config as a fallback
      return themeConfig.sidebar ? themeConfig.sidebar["/"] || [] : [];
    },
  },
};
</script>

<style scoped>
.NotFound {
  text-align: center;
  padding: 2em;
}
</style>

// src/app/not-found.tsx
import { Button } from '@/components/Button'
import { HeroPattern } from '@/components/HeroPattern'
import { SquareArrowOutUpRight } from 'lucide-react'

export default function NotFound() {
  return (
    <>
      <HeroPattern />
      <div className="mx-auto flex h-full max-w-xl flex-col items-center justify-center py-16 text-center">
        <p className="text-lg text-zinc-900 dark:text-white">404s suck!</p>
        <img src="https://arweave.net/JluJoV__SITJWXvtzkoKvsMoRqQOWnvVX7G6kAj2RdU"></img>
        <h1 className="mt-2 text-2xl font-semibold text-zinc-900 dark:text-zinc-400">
          Good thing the permaweb has
        </h1>
        <p className="mt-2 text-2xl font-bold text-zinc-600 underline dark:text-white">
          <a
            href="https://ardrive.io/fragility-of-the-internet/"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center"
          >
            {' '}
            no more 404s <SquareArrowOutUpRight className="w-4 h-4"/>
          </a>
        </p>
        <Button href="/" arrow="right" className="mt-8">
          Back to Home
        </Button>
      </div>
    </>
  )
}
